apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::477781350243:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-GHJO2RDT6GV3
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::477781350243:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-22T18:00:06Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1409"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 85ce13c1-39b5-4494-a18c-11d75ce2d0f6